putall fails because prompt attribute is missing
AttributeError: 'Namespace' object has no attribute 'prompt'

It's not needed for this operation anyhow.